
the

AT-GC-AA-GA-AAATTTGTGAGAACAAAACCGCATGTTAACGTTGGAACATGGCGAAGG
AAAAATTTGTGAGAACAAAACCGCATGTTAACGTTGGAAC1
;
TeH
--AT-GC-AA-GA-AAATTTGTGAGAACAAAACCGCATGTTAACGTTGGAACATGGCGAA
AACGCGTAGTAGCGACTCG----CGTAGC--CGATC----2
