/* Generated By:JavaCC: Do not edit this line. BibtexParserConstants.java */
package de.unibi.cebitec.bibiserv.util.bibtexparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BibtexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AT = 1;
  /** RegularExpression Id. */
  int WS = 2;
  /** RegularExpression Id. */
  int STR = 3;
  /** RegularExpression Id. */
  int PRE = 4;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int EQ = 6;
  /** RegularExpression Id. */
  int HASH = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int QUOTE = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int DELIM = 14;
  /** RegularExpression Id. */
  int QCHAR = 15;
  /** RegularExpression Id. */
  int WORD = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int SIGN = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"@\"",
    "<WS>",
    "\"string\"",
    "\"preamble\"",
    "\"comment\"",
    "\"=\"",
    "\"#\"",
    "<COMMA>",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "<DELIM>",
    "<QCHAR>",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
  };

}
