
the

AU-GC-AA-GA-AAAUUUGUGAGAACAAAACCGCAUGUUAACGUUGGAACAUGGCGAAGG
AAAAAUUUGUGAGAACAAAACCGCAUGUUAACGUUGGAAC1
;
TeH
--AU-GC-AA-GA-AAAUUUGUGAGAACAAAACCGCAUGUUAACGUUGGAACAUGGCGAA
AACGCGUAGUAGCGACUCG----CGUAGC--CGAUC----2
